### PR TITLE
added random problem selector

### PR DESCRIPTION
**Pull request by explise**

### CODE REVIEW

**Review by theabbie — APPROVED** [review]
LGTM

**Review by theSoberSobber — CHANGES_REQUESTED** [review]
Hey, thanks for the PR. Some points - 
- why'd you remove the descending order sorting?
- please remove the debug print api key, or hide under some debug env variable
- the random.html, could you attach some screenshots in the PR for reference purposes?

**Comment by theSoberSobber** [comment]
also, sorry for another nitpick, but would it be possible to add a something like this instead?
image
you have a rating range above and the paginated list shows the filtered list on the main page itself, and there is a random button next to it that respects the rating range rules if any.

**Comment by theSoberSobber** [comment]
Hey @explise @theabbie, I am closing this PR since it's redundant with https://github.com/theSoberSobber/leetcode-problem-ratings/commit/bb75a8781f454df12c0485f4847c365119516ad0. Thanks for the PR, I appreciate it.

**Pull request closed without merging**
